# Generated by Django 4.1.5 on 2023-01-05 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_id',
            new_name='iid',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='item_type',
            new_name='types',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='record_id',
            new_name='rid',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='test_id',
            new_name='test',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_id',
            new_name='sid',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='test_id',
            new_name='tid',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='time',
            new_name='total_time',
        ),
    ]
