# Generated by Django 4.1.5 on 2023-01-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_rename_item_id_item_iid_rename_item_type_item_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='student',
            field=models.ManyToManyField(to='exam.student', verbose_name='考生列表'),
        ),
    ]
