# Generated by Django 4.1.5 on 2023-01-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_test_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.CharField(choices=[('G1', '一年级'), ('G2', '二年级'), ('G3', '三年级'), ('G4', '四年级'), ('G5', '五年级'), ('G6', '六年级'), ('G7', '七年级'), ('G8', '八年级'), ('G9', '九年级')], default='G1', max_length=50),
        ),
    ]
