# Generated by Django 4.1.5 on 2023-01-11 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_student_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='pwd',
        ),
        migrations.AddField(
            model_name='student',
            name='extend_data',
            field=models.JSONField(blank=True, default=1, help_text='用于扩展当前收集的人口统计学变量', verbose_name='其他'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(blank=True, choices=[('G1', '一年级'), ('G2', '二年级'), ('G3', '三年级'), ('G4', '四年级'), ('G5', '五年级'), ('G6', '六年级'), ('G7', '七年级'), ('G8', '八年级'), ('G9', '九年级')], default='G1', max_length=50, verbose_name='年级'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.BooleanField(blank=True, choices=[(0, '女'), (1, '男')], default=0, verbose_name='性别'),
        ),
    ]
