# Generated by Django 4.1.5 on 2023-01-11 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_remove_student_name_remove_student_pwd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='extend_data',
            field=models.JSONField(help_text='用于扩展当前收集的人口统计学变量', null=True, verbose_name='其他'),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(choices=[('G1', '一年级'), ('G2', '二年级'), ('G3', '三年级'), ('G4', '四年级'), ('G5', '五年级'), ('G6', '六年级'), ('G7', '七年级'), ('G8', '八年级'), ('G9', '九年级')], default='G1', max_length=50, null=True, verbose_name='年级'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.BooleanField(choices=[(0, '女'), (1, '男')], default=0, null=True, verbose_name='性别'),
        ),
    ]
