# Generated by Django 4.1.5 on 2023-01-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_alter_student_extend_data_alter_student_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(choices=[('G1', '一年级'), ('G2', '二年级'), ('G3', '三年级'), ('G4', '四年级'), ('G5', '五年级'), ('G6', '六年级'), ('G7', '七年级'), ('G8', '八年级'), ('G9', '九年级')], max_length=50, null=True, verbose_name='年级'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.BooleanField(choices=[(0, '女'), (1, '男')], null=True, verbose_name='性别'),
        ),
    ]
